projects:
  app:
    schemaPath: src/schema/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:8080
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
      codegen:
      - generator: prisma-binding
        language: typescript
        output:
          binding: src/generated/prisma.ts
  